name: Actions Javascript

on:
  repository_dispatch:
    types:
      - build
  pull_request:
    types:
      - assigned
      - closed
      - opened
      - reopened

# o arquivo aqui e actions porque e custom
# por padrão o metadata e action.yml ou action.yaml

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List of files
        run: |
          pwd
          ls -a
          echo repository  $GITHUB_REPOSITORY
          echo hash commit $GITHUB_SHA
          echo autor $GITHUB_ACTOR
      - name: checkout
        uses: actions/checkout@v2
      - name: List of files after checkout
        # a partir daqui consigo ver os arquivos locais #
        run: |
          pwd 
          ls -a
      - name: payload client_payload
        run: echo payload of the client  ${{ github.event.client_payload.env }}
      - name: Simple JS Action
        id: greeting
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: "Kenji"
      - name: Print name login
        run: |
          echo "${{ steps.greeting.outputs.time }}"
