name: Context testing

env:
  ARRAY:
    - banaa
    - maca
    - pera

on: push

# https://docs.github.com/en/actions/learn-github-actions/contexts#functions

#https://docs.github.com/en/actions/learn-github-actions/contexts

#https://docs.github.com/en/actions/learn-github-actions/expressions#tojson
jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: Functions available
        # repara nas aspas simples
        run: |
          echo ${{ contains($ARRAY,banana) }}
          echo ${{ startsWith('Hello', 'H') }}
          echo ${{ endsWith('Hello', 'o') }}
          echo ${{ format('Hello {0} {1} {2}', 'Mona', 'the', 'Octocat') }}

  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo $GITHUB_CONTEXT
      - name: Dumb Job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo $JOB_CONTEXT
      - name: Dumb steps context
        env:
          STEEPS_CONTEXT: ${{ toJSON(steps)  }}
        run: echo $STEEPS_CONTEXT
      - name: Dumb runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo $RUNNER_CONTEXT
      - name: Dumb matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo $MATRIX_CONTEXT
      - name: Dumb strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo $STRATEGY_CONTEXT
