name: Work Flow Shell

on: [pull_request]

jobs:
  run-shell-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "Hello World"
        continue-on-error: true
      - name: multiline
        run: |
          pwd
          node --version
      - name: shell with python
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-shell-window:
    runs-on: windows-latest
    needs: ["run-shell-ubuntu"]
    steps:
      - name: use command windows
        run: GET-LOCATION
      - name: use equal commands on bash
        run: pwd
        shell: bash
